<?php

/**
 * PluginApiAuthenticationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginApiAuthenticationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginApiAuthenticationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginApiAuthentication');
    }
}