<?php

/**
 * PluginEmployeeMultiSourceFeedbackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmployeeMultiSourceFeedbackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmployeeMultiSourceFeedbackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmployeeMultiSourceFeedback');
    }
}