<?php

/**
 * PluginPerformanceReviewReviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPerformanceReviewReviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPerformanceReviewReviewerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerformanceReviewReviewer');
    }
}