<?php

/**
 * PluginPerformancePeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPerformancePeriodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPerformancePeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerformancePeriod');
    }
}