<?php

/**
 * PluginPerformanceAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPerformanceAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPerformanceAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerformanceAttachment');
    }
}