<?php

/**
 * BaseLeaveCompOff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $emp_number
 * @property integer $number_of_days
 * @property string $compoff_details
 * @property integer $status
 * @property date $created_date
 * @property date $updated_date
 * @property Employee $Employee
 * 
 * @method integer      getId()              Returns the current record's "id" value
 * @method integer      getEmpNumber()       Returns the current record's "emp_number" value
 * @method integer      getNumberOfDays()    Returns the current record's "number_of_days" value
 * @method string       getCompoffDetails()  Returns the current record's "compoff_details" value
 * @method integer      getStatus()          Returns the current record's "status" value
 * @method date         getCreatedDate()     Returns the current record's "created_date" value
 * @method date         getUpdatedDate()     Returns the current record's "updated_date" value
 * @method Employee     getEmployee()        Returns the current record's "Employee" value
 * @method LeaveCompOff setId()              Sets the current record's "id" value
 * @method LeaveCompOff setEmpNumber()       Sets the current record's "emp_number" value
 * @method LeaveCompOff setNumberOfDays()    Sets the current record's "number_of_days" value
 * @method LeaveCompOff setCompoffDetails()  Sets the current record's "compoff_details" value
 * @method LeaveCompOff setStatus()          Sets the current record's "status" value
 * @method LeaveCompOff setCreatedDate()     Sets the current record's "created_date" value
 * @method LeaveCompOff setUpdatedDate()     Sets the current record's "updated_date" value
 * @method LeaveCompOff setEmployee()        Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveCompOff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_comp_off');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('number_of_days', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('compoff_details', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('created_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}