<?php

/**
 * BaseTrainingTrainer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trainerType
 * @property integer $training_id
 * @property integer $emp_number
 * @property integer $trainer_id
 * @property Doctrine_Collection $Trainer
 * @property Doctrine_Collection $TrainerEmployee
 * @property Training $Training
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getTrainerType()     Returns the current record's "trainerType" value
 * @method integer             getTrainingId()      Returns the current record's "training_id" value
 * @method integer             getEmpNumber()       Returns the current record's "emp_number" value
 * @method integer             getTrainerId()       Returns the current record's "trainer_id" value
 * @method Doctrine_Collection getTrainer()         Returns the current record's "Trainer" collection
 * @method Doctrine_Collection getTrainerEmployee() Returns the current record's "TrainerEmployee" collection
 * @method Training            getTraining()        Returns the current record's "Training" value
 * @method TrainingTrainer     setId()              Sets the current record's "id" value
 * @method TrainingTrainer     setTrainerType()     Sets the current record's "trainerType" value
 * @method TrainingTrainer     setTrainingId()      Sets the current record's "training_id" value
 * @method TrainingTrainer     setEmpNumber()       Sets the current record's "emp_number" value
 * @method TrainingTrainer     setTrainerId()       Sets the current record's "trainer_id" value
 * @method TrainingTrainer     setTrainer()         Sets the current record's "Trainer" collection
 * @method TrainingTrainer     setTrainerEmployee() Sets the current record's "TrainerEmployee" collection
 * @method TrainingTrainer     setTraining()        Sets the current record's "Training" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrainingTrainer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_trainer');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('trainer_type as trainerType', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('training_id', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('trainer_id', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Trainer', array(
             'local' => 'trainer_id',
             'foreign' => 'id'));

        $this->hasOne('Employee as TrainerEmployee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('Training', array(
             'local' => 'training_id',
             'foreign' => 'id'));
    }
}