<?php

/**
 * BaseTrainer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $firstName
 * @property string $lastName
 * @property string $details
 * @property integer $isDeleted
 * @property Doctrine_Collection $Training
 * @property TrainingTrainer $TrainingTrainer
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getFirstName()       Returns the current record's "firstName" value
 * @method string              getLastName()        Returns the current record's "lastName" value
 * @method string              getDetails()         Returns the current record's "details" value
 * @method integer             getIsDeleted()       Returns the current record's "isDeleted" value
 * @method Doctrine_Collection getTraining()        Returns the current record's "Training" collection
 * @method TrainingTrainer     getTrainingTrainer() Returns the current record's "TrainingTrainer" value
 * @method Trainer             setId()              Sets the current record's "id" value
 * @method Trainer             setFirstName()       Sets the current record's "firstName" value
 * @method Trainer             setLastName()        Sets the current record's "lastName" value
 * @method Trainer             setDetails()         Sets the current record's "details" value
 * @method Trainer             setIsDeleted()       Sets the current record's "isDeleted" value
 * @method Trainer             setTraining()        Sets the current record's "Training" collection
 * @method Trainer             setTrainingTrainer() Sets the current record's "TrainingTrainer" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrainer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_trainer');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('first_name as firstName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('last_name as lastName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('details', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_deleted as isDeleted', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Training', array(
             'local' => 'id',
             'foreign' => 'trainer'));

        $this->hasOne('TrainingTrainer', array(
             'local' => 'id',
             'foreign' => 'trainer_id'));
    }
}