<?php

/**
 * BaseTrainingAttendance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empNumber
 * @property integer $scheduleId
 * 
 * @method integer            getId()         Returns the current record's "id" value
 * @method integer            getEmpNumber()  Returns the current record's "empNumber" value
 * @method integer            getScheduleId() Returns the current record's "scheduleId" value
 * @method TrainingAttendance setId()         Sets the current record's "id" value
 * @method TrainingAttendance setEmpNumber()  Sets the current record's "empNumber" value
 * @method TrainingAttendance setScheduleId() Sets the current record's "scheduleId" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrainingAttendance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_attendance');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('emp_number as empNumber', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('schedule_id as scheduleId', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}