<?php

/**
 * BaseTrainingPoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empNumber
 * @property integer $trainingId
 * @property integer $points
 * @property integer $action
 * @property integer $added_by
 * @property Training $Training
 * @property Employee $Employee
 * @property Employee $AddedBy
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getEmpNumber()  Returns the current record's "empNumber" value
 * @method integer       getTrainingId() Returns the current record's "trainingId" value
 * @method integer       getPoints()     Returns the current record's "points" value
 * @method integer       getAction()     Returns the current record's "action" value
 * @method integer       getAddedBy()    Returns the current record's "added_by" value
 * @method Training      getTraining()   Returns the current record's "Training" value
 * @method Employee      getEmployee()   Returns the current record's "Employee" value
 * @method Employee      getAddedBy()    Returns the current record's "AddedBy" value
 * @method TrainingPoint setId()         Sets the current record's "id" value
 * @method TrainingPoint setEmpNumber()  Sets the current record's "empNumber" value
 * @method TrainingPoint setTrainingId() Sets the current record's "trainingId" value
 * @method TrainingPoint setPoints()     Sets the current record's "points" value
 * @method TrainingPoint setAction()     Sets the current record's "action" value
 * @method TrainingPoint setAddedBy()    Sets the current record's "added_by" value
 * @method TrainingPoint setTraining()   Sets the current record's "Training" value
 * @method TrainingPoint setEmployee()   Sets the current record's "Employee" value
 * @method TrainingPoint setAddedBy()    Sets the current record's "AddedBy" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrainingPoint extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_points');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('emp_number as empNumber', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('training_id as trainingId', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('points', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('action', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('added_by', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Training', array(
             'local' => 'training_id',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('Employee as AddedBy', array(
             'local' => 'added_by',
             'foreign' => 'emp_number'));
    }
}