<?php

/**
 * BaseTrainingSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trainingId
 * @property date $sessionDate
 * @property string $topic
 * @property text $description
 * @property Training $Training
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method integer          getTrainingId()  Returns the current record's "trainingId" value
 * @method date             getSessionDate() Returns the current record's "sessionDate" value
 * @method string           getTopic()       Returns the current record's "topic" value
 * @method text             getDescription() Returns the current record's "description" value
 * @method Training         getTraining()    Returns the current record's "Training" value
 * @method TrainingSchedule setId()          Sets the current record's "id" value
 * @method TrainingSchedule setTrainingId()  Sets the current record's "trainingId" value
 * @method TrainingSchedule setSessionDate() Sets the current record's "sessionDate" value
 * @method TrainingSchedule setTopic()       Sets the current record's "topic" value
 * @method TrainingSchedule setDescription() Sets the current record's "description" value
 * @method TrainingSchedule setTraining()    Sets the current record's "Training" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrainingSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_schedule');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('training_id as trainingId', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('session_date as sessionDate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('topic', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
		$this->hasColumn('from_time as fromTime', 'time', 10, array(
			'type' => 'time',
			'length' => 10,
			));
        $this->hasColumn('to_time as toTime', 'time', 10, array(
            'type' => 'time',
            'length' => 10,
            ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Training', array(
             'local' => 'training_id',
             'foreign' => 'id'));
    }
}