<?php

/**
 * BaseTraining
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $topic
 * @property string $description
 * @property integer $attendeePoint
 * @property integer $trainerPoint
 * @property double $totalHours
 * @property date $fromDate
 * @property date $toDate
 * @property string $location
 * @property date $createdDate
 * @property date $updatedDate
 * @property integer $createdBy
 * @property integer $updatedBy
 * @property integer $isPublished
 * @property integer $isDeleted
 * @property Doctrine_Collection $TrainingSchedule
 * @property Doctrine_Collection $TrainingTrainer
 * @property Doctrine_Collection $TrainingAttendees
 * @property Trainer $Trainer
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getTopic()             Returns the current record's "topic" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method integer             getAttendeePoint()     Returns the current record's "attendeePoint" value
 * @method integer             getTrainerPoint()      Returns the current record's "trainerPoint" value
 * @method double              getTotalHours()        Returns the current record's "totalHours" value
 * @method string              getLocation()          Returns the current record's "location" value
 * @method date                getCreatedDate()       Returns the current record's "createdDate" value
 * @method date                getUpdatedDate()       Returns the current record's "updatedDate" value
 * @method integer             getCreatedBy()         Returns the current record's "createdBy" value
 * @method integer             getUpdatedBy()         Returns the current record's "updatedBy" value
 * @method integer             getIsPublished()       Returns the current record's "isPublished" value
 * @method integer             getIsDeleted()         Returns the current record's "isDeleted" value
 * @method Doctrine_Collection getTrainingSchedule()  Returns the current record's "TrainingSchedule" collection
 * @method Doctrine_Collection getTrainingTrainer()   Returns the current record's "TrainingTrainer" collection
 * @method Doctrine_Collection getTrainingAttendees() Returns the current record's "TrainingAttendees" collection
 * @method Trainer             getTrainer()           Returns the current record's "Trainer" value
 * @method Training            setId()                Sets the current record's "id" value
 * @method Training            setTopic()             Sets the current record's "topic" value
 * @method Training            setDescription()       Sets the current record's "description" value
 * @method Training            setAttendeePoint()     Sets the current record's "attendeePoint" value
 * @method Training            setTrainerPoint()      Sets the current record's "trainerPoint" value
 * @method Training            setTotalHours()        Sets the current record's "totalHours" value
 * @method Training            setLocation()          Sets the current record's "location" value
 * @method Training            setCreatedDate()       Sets the current record's "createdDate" value
 * @method Training            setUpdatedDate()       Sets the current record's "updatedDate" value
 * @method Training            setCreatedBy()         Sets the current record's "createdBy" value
 * @method Training            setUpdatedBy()         Sets the current record's "updatedBy" value
 * @method Training            setIsPublished()       Sets the current record's "isPublished" value
 * @method Training            setIsDeleted()         Sets the current record's "isDeleted" value
 * @method Training            setTrainingSchedule()  Sets the current record's "TrainingSchedule" collection
 * @method Training            setTrainingTrainer()   Sets the current record's "TrainingTrainer" collection
 * @method Training            setTrainingAttendees() Sets the current record's "TrainingAttendees" collection
 * @method Training            setTrainer()           Sets the current record's "Trainer" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTraining extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training');
        $this->hasColumn('id as id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('topic', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('description as description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('attendee_point as attendeePoint', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('trainer_point as trainerPoint', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('total_hours as totalHours', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('location', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('created_date as createdDate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('updated_date as updatedDate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('created_by as createdBy', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('updated_by as updatedBy', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('is_published as isPublished', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'length' => 1,
             ));
        $this->hasColumn('is_deleted as isDeleted', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TrainingSchedule', array(
             'local' => 'id',
             'foreign' => 'training_id'));

        $this->hasMany('TrainingTrainer', array(
             'local' => 'id',
             'foreign' => 'training_id'));

        $this->hasMany('TrainingAttendees', array(
             'local' => 'id',
             'foreign' => 'training_id'));

    }
}