<?php

/**
 * BaseTrainingAttendees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empNumber
 * @property integer $training_id
 * @property date $regDate
 * @property Doctrine_Collection $Employee
 * @property Training $Training
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getEmpNumber()   Returns the current record's "empNumber" value
 * @method integer             getTrainingId()  Returns the current record's "training_id" value
 * @method date                getRegDate()     Returns the current record's "regDate" value
 * @method Doctrine_Collection getEmployee()    Returns the current record's "Employee" collection
 * @method Training            getTraining()    Returns the current record's "Training" value
 * @method TrainingAttendees   setId()          Sets the current record's "id" value
 * @method TrainingAttendees   setEmpNumber()   Sets the current record's "empNumber" value
 * @method TrainingAttendees   setTrainingId()  Sets the current record's "training_id" value
 * @method TrainingAttendees   setRegDate()     Sets the current record's "regDate" value
 * @method TrainingAttendees   setEmployee()    Sets the current record's "Employee" collection
 * @method TrainingAttendees   setTraining()    Sets the current record's "Training" value
 * 
 * @package    orangehrm
 * @subpackage model\training\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrainingAttendees extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_attendees');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('emp_number as empNumber', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('training_id as trainingId', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('reg_date as regDate', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'empNumber',
             'foreign' => 'emp_number'));

        $this->hasOne('Training', array(
             'local' => 'training_id',
             'foreign' => 'id'));
    }
}