<?php

/**
 * PluginLocation class file
 */

/**
 * PluginLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginLocation extends BaseLocation
{
	const LOCATION_ACTIVE_FOR_ATTENDANCE_SYSTEM = 1;
}