<?php

/**
 * PluginEmploymentStatus class file
 */

/**
 * PluginEmploymentStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginEmploymentStatus extends BaseEmploymentStatus
{
	const STATUS_FULLTIME_PERMENANT = 4;
	const STATUS_FULLTIME_PROBATION = 5;
}