<?php

/**
 * BaseApiAuthentication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $apiKey
 * @property integer $empNumber
 * @property datetime $createdAt
 * @property Employee $Employee
 * 
 * @method integer           getId()        Returns the current record's "id" value
 * @method string            getApiKey()    Returns the current record's "apiKey" value
 * @method integer           getEmpNumber() Returns the current record's "empNumber" value
 * @method datetime          getCreatedAt() Returns the current record's "createdAt" value
 * @method Employee          getEmployee()  Returns the current record's "Employee" value
 * @method ApiAuthentication setId()        Sets the current record's "id" value
 * @method ApiAuthentication setApiKey()    Sets the current record's "apiKey" value
 * @method ApiAuthentication setEmpNumber() Sets the current record's "empNumber" value
 * @method ApiAuthentication setCreatedAt() Sets the current record's "createdAt" value
 * @method ApiAuthentication setEmployee()  Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\sfrestwebservice\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApiAuthentication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_api_authentication');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 10,
             ));
        $this->hasColumn('api_key as apiKey', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('emp_number as empNumber', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('created_at as createdAt', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'empNumber',
             'foreign' => 'emp_number'));
    }
}