<?php

/**
 * ApiAuthenticationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiAuthenticationTable extends PluginApiAuthenticationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiAuthenticationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApiAuthentication');
    }
}