<?php

/**
 * PluginJobVacancyHiringManagerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobVacancyHiringManagerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobVacancyHiringManagerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobVacancyHiringManager');
    }
}