<?php

/**
 * PluginInterviewFeedbackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInterviewFeedbackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginInterviewFeedbackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginInterviewFeedback');
    }
}