<?php

/**
 * PluginJobCandidateRequestsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobCandidateRequestsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobCandidateRequestsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobCandidateRequests');
    }
}