<?php

/**
 * TrainingAttendeesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrainingAttendeesTable extends PluginTrainingAttendeesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrainingAttendeesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrainingAttendees');
    }
}