<?php

/**
 * TrainingTrainer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrainingTrainer extends PluginTrainingTrainer
{
	public function getTrainerObject() {
		if($this->getTrainerType() == parent::INTERNAL_TRAINER) {
			return $this->getTrainerEmployee();
		} else {
			return $this->getTrainer();
		}
	}
	
	public function getTrainerFirstAndLastNames() {
		if($this->getTrainerType() == parent::INTERNAL_TRAINER) {
			return $this->getTrainerEmployee()->getFirstAndLastNames();
		} else {
			return $this->getTrainer()->getFirstAndLastNames();
		}
	}
}