<?php

/**
 * TrainingAttendanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrainingAttendanceTable extends PluginTrainingAttendanceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrainingAttendanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrainingAttendance');
    }
}