<?php

/**
 * TrainingScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrainingScheduleTable extends PluginTrainingScheduleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrainingScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrainingSchedule');
    }
}