<?php

/**
 * TrainingPointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrainingPointTable extends PluginTrainingPointTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrainingPointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrainingPoint');
    }
}