<?php

/**
 * TrainerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrainerTable extends PluginTrainerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrainerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trainer');
    }
}