<?php

/**
 * EmployeeCertification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmployeeCertification extends BaseEmployeeCertification
{
	 const CERTIFICATE_APPROVE = '1';
	 const CERTIFICATE_NOT_APPROVE = '0';
}