<?php

/**
 * EmployeeCertificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmployeeCertificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmployeeCertificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmployeeCertification');
    }
}