<?php

/**
 * BaseInterviewFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $historyId
 * @property string $soft_skill
 * @property string $attitude
 * @property string $communication
 * @property string $comments
 * @property Doctrine_Collection $CandidateHistory
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getHistoryId()        Returns the current record's "historyId" value
 * @method string              getSoftSkill()        Returns the current record's "soft_skill" value
 * @method string              getAttitude()         Returns the current record's "attitude" value
 * @method string              getCommunication()    Returns the current record's "communication" value
 * @method string              getComments()         Returns the current record's "comments" value
 * @method Doctrine_Collection getCandidateHistory() Returns the current record's "CandidateHistory" collection
 * @method InterviewFeedback   setId()               Sets the current record's "id" value
 * @method InterviewFeedback   setHistoryId()        Sets the current record's "historyId" value
 * @method InterviewFeedback   setSoftSkill()        Sets the current record's "soft_skill" value
 * @method InterviewFeedback   setAttitude()         Sets the current record's "attitude" value
 * @method InterviewFeedback   setCommunication()    Sets the current record's "communication" value
 * @method InterviewFeedback   setComments()         Sets the current record's "comments" value
 * @method InterviewFeedback   setCandidateHistory() Sets the current record's "CandidateHistory" collection
 * 
 * @package    orangehrm
 * @subpackage model\recruitment\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInterviewFeedback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_interview_feedback');
        $this->hasColumn('id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 13,
             ));
        $this->hasColumn('history_id as historyId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('soft_skill', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('attitude', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('communication', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('comments', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CandidateHistory', array(
             'local' => 'historyId',
             'foreign' => 'id'));
    }
}