<?php

/**
 * BaseJobCandidateRequests
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $request_id
 * @property integer $candidateId
 * @property integer $oldVacancyId
 * @property integer $newVacancyId
 * @property integer $request_status
 * @property integer $createdBy
 * @property datetime $createdDate
 * @property integer $updatedBy
 * @property datetime $updatedDate
 * @property JobVacancy $JobVacancy
 * @property JobCandidate $JobCandidate
 * 
 * @method integer              getRequestId()      Returns the current record's "request_id" value
 * @method integer              getCandidateId()    Returns the current record's "candidateId" value
 * @method integer              getOldVacancyId()   Returns the current record's "oldVacancyId" value
 * @method integer              getNewVacancyId()   Returns the current record's "newVacancyId" value
 * @method integer              getRequestStatus()  Returns the current record's "request_status" value
 * @method integer              getCreatedBy()      Returns the current record's "createdBy" value
 * @method datetime             getCreatedDate()    Returns the current record's "createdDate" value
 * @method integer              getUpdatedBy()      Returns the current record's "updatedBy" value
 * @method datetime             getUpdatedDate()    Returns the current record's "updatedDate" value
 * @method JobVacancy  			getOldJobVacancy()  Returns the current record's "JobVacancy" collection
 * @method JobVacancy  			getNewJobVacancy()  Returns the current record's "JobVacancy" collection
 * @method JobCandidate  		getJobCandidate()   Returns the current record's "JobCandidate" collection
 * @method JobCandidateRequests setRequestId()      Sets the current record's "request_id" value
 * @method JobCandidateRequests setCandidateId()    Sets the current record's "candidateId" value
 * @method JobCandidateRequests setOldVacancyId()   Sets the current record's "oldVacancyId" value
 * @method JobCandidateRequests setNewVacancyId()   Sets the current record's "newVacancyId" value
 * @method JobCandidateRequests setRequestStatus()  Sets the current record's "request_status" value
 * @method JobCandidateRequests setCreatedBy()      Sets the current record's "createdBy" value
 * @method JobCandidateRequests setCreatedDate()    Sets the current record's "createdDate" value
 * @method JobCandidateRequests setUpdatedBy()      Sets the current record's "updatedBy" value
 * @method JobCandidateRequests setUpdatedDate()    Sets the current record's "updatedDate" value
 * @method JobCandidateRequests setOldJobVacancy()  Sets the current record's "JobVacancy" collection
 * @method JobCandidateRequests setNewJobVacancy()  Sets the current record's "JobVacancy" collection
 * @method JobCandidateRequests setJobCandidate()   Sets the current record's "JobCandidate" collection
 * 
 * @package    orangehrm
 * @subpackage model\recruitment\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobCandidateRequests extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_job_candidate_requests');
        $this->hasColumn('request_id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 13,
             ));
        $this->hasColumn('candidate_id as candidateId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('old_vacancy_id as oldVacancyId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('new_vacancy_id as newVacancyId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('request_status', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('request_type', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('created_by as createdBy', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('created_date as createdDate', 'date', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('updated_by as updatedBy', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('updated_date as updatedDate', 'date', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
        $this->hasOne('JobVacancy as oldJobVacancy', array(
             'local' => 'oldVacancyId',
             'foreign' => 'id'));
             
        $this->hasOne('JobVacancy as newJobVacancy', array(
             'local' => 'newVacancyId',
             'foreign' => 'id'));

        $this->hasOne('JobCandidate', array(
             'local' => 'candidateId',
             'foreign' => 'id'));
        
        $this->hasOne('Employee', array(
             'local' => 'createdBy',
             'foreign' => 'empNumber'));
    }
}