<?php

/**
 * BaseJobVacancyHiringManager
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vacancyId
 * @property integer $hiringManagerId
 * @property Employee $Employee
 * @property JobVacancy $JobVacancy
 * 
 * @method integer                 getId()              Returns the current record's "id" value
 * @method integer                 getVacancyId()       Returns the current record's "vacancyId" value
 * @method integer                 getHiringManagerId() Returns the current record's "hiringManagerId" value
 * @method Employee                getEmployee()        Returns the current record's "Employee" value
 * @method JobVacancy              getJobVacancy()      Returns the current record's "JobVacancy" value
 * @method JobVacancyHiringManager setId()              Sets the current record's "id" value
 * @method JobVacancyHiringManager setVacancyId()       Sets the current record's "vacancyId" value
 * @method JobVacancyHiringManager setHiringManagerId() Sets the current record's "hiringManagerId" value
 * @method JobVacancyHiringManager setEmployee()        Sets the current record's "Employee" value
 * @method JobVacancyHiringManager setJobVacancy()      Sets the current record's "JobVacancy" value
 * 
 * @package    orangehrm
 * @subpackage model\recruitment\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobVacancyHiringManager extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_job_vacancy_hiring_manager');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('vacancy_id as vacancyId', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('hiring_manager_id as hiringManagerId', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'hiring_manager_id',
             'foreign' => 'emp_number'));

        $this->hasOne('JobVacancy', array(
             'local' => 'vacancy_id',
             'foreign' => 'id'));
    }
}