<?php

/**
 * BaseResetPassword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $uniqueKey
 * @property string $empId
 * @property timestamp $createdTime
 * @property string $active
 * @property Doctrine_Collection $Employee
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getUniqueKey()   Returns the current record's "uniqueKey" value
 * @method string              getEmpId()       Returns the current record's "empId" value
 * @method timestamp           getCreatedTime() Returns the current record's "createdTime" value
 * @method string              getActive()      Returns the current record's "active" value
 * @method Doctrine_Collection getEmployee()    Returns the current record's "Employee" collection
 * @method ResetPassword       setId()          Sets the current record's "id" value
 * @method ResetPassword       setUniqueKey()   Sets the current record's "uniqueKey" value
 * @method ResetPassword       setEmpId()       Sets the current record's "empId" value
 * @method ResetPassword       setCreatedTime() Sets the current record's "createdTime" value
 * @method ResetPassword       setActive()      Sets the current record's "active" value
 * @method ResetPassword       setEmployee()    Sets the current record's "Employee" collection
 * 
 * @package    orangehrm
 * @subpackage model\core\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResetPassword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user_reset_password');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('unique_key as uniqueKey', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('emp_id as empId', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('created_time as createdTime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Employee', array(
             'local' => 'emp_id',
             'foreign' => 'emp_number'));
    }
}