<?php

/**
 * JobTitle class file
 */

/**
 * JobTitle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class JobTitle extends PluginJobTitle
{
    const NO_OF_RECORDS_PER_PAGE = 10;
    const DELETED = 1;
    const ACTIVE = 0;

}
