<?php

/**
 * EmployeeMultiSourceFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmployeeMultiSourceFeedback extends BaseEmployeeMultiSourceFeedback
{
	CONST IS_SUBMITTED = 1;
	CONST IS_NOT_SUBMITTED = 0;
	CONST IS_DELETED = 1;
	CONST IS_NOT_DELETED = 0;
	CONST IS_ANONYMOUS = 1;
	CONST IS_NOT_ANONYMOUS = 0;
}