<?php

/**
 * PerformanceAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerformanceAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerformanceAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerformanceAttachment');
    }
}