<?php

/**
 * PerformancePeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerformancePeriodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerformancePeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerformancePeriod');
    }
}