<?php

/**
 * PerformanceReviewReviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerformanceReviewReviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerformanceReviewReviewerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerformanceReviewReviewer');
    }
}