<?php

/**
 * PluginTrainingPointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingPointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingPointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTrainingPoint');
    }
}