<?php

/**
 * PluginTrainingScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingScheduleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTrainingSchedule');
    }
}