<?php

/**
 * PluginTrainingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTraining');
    }
}