<?php

/**
 * PluginTraining
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginTraining extends BaseTraining
{
	const IS_PUBLISHED = 1;
	const IS_NOT_PUBLISHED = 0;
	const IS_DELETED = 1;
	const IS_NOT_DELETED = 0;
}