<?php

/**
 * PluginTrainingAttendanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingAttendanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingAttendanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTrainingAttendance');
    }
}