<?php

/**
 * PluginTrainingAttendeesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingAttendeesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingAttendeesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTrainingAttendees');
    }
}