<?php

/**
 * PluginTrainingTrainerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingTrainerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingTrainerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTrainingTrainer');
    }
}