<?php

/**
 * BasePerformancePeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $periodFrom
 * @property date $periodTo
 * @property date $dueDate
 * @property timestamp $createdDate
 * 
 * @method integer           getId()          Returns the current record's "id" value
 * @method date              getPeriodFrom()  Returns the current record's "periodFrom" value
 * @method date              getPeriodTo()    Returns the current record's "periodTo" value
 * @method date              getDueDate()     Returns the current record's "dueDate" value
 * @method timestamp         getCreatedDate() Returns the current record's "createdDate" value
 * @method PerformancePeriod setId()          Sets the current record's "id" value
 * @method PerformancePeriod setPeriodFrom()  Sets the current record's "periodFrom" value
 * @method PerformancePeriod setPeriodTo()    Sets the current record's "periodTo" value
 * @method PerformancePeriod setDueDate()     Sets the current record's "dueDate" value
 * @method PerformancePeriod setCreatedDate() Sets the current record's "createdDate" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerformancePeriod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_performance_period');
        $this->hasColumn('id as id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('period_from as periodFrom', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('period_to as periodTo', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('due_date as dueDate', 'date', null, array(
             'type' => 'date',
             ));
        /*Added by sujata*/
        $this->hasColumn('one_on_one_review_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('self_review_date', 'date', null, array(
             'type' => 'date',
             ));
             
        $this->hasColumn('created_date as createdDate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}