<?php

/**
 * BasePerformanceReviewReviewer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reviewId
 * @property integer $reviewerId
 * @property string $kpis
 * @property PerformanceReview $PerformanceReview
 * @property Employee $Reviewer
 * 
 * @method integer                   getId()                Returns the current record's "id" value
 * @method integer                   getReviewId()          Returns the current record's "reviewId" value
 * @method integer                   getReviewerId()        Returns the current record's "reviewerId" value
 * @method string                    getKpis()              Returns the current record's "kpis" value
 * @method string              		 getRatings()           Returns the current record's "ratings" value
 * @method PerformanceReview         getPerformanceReview() Returns the current record's "PerformanceReview" collection
 * @method Employee                  getReviewer()          Returns the current record's "Reviewer" value
 * @method PerformanceReviewReviewer setId()                Sets the current record's "id" value
 * @method PerformanceReviewReviewer setReviewId()          Sets the current record's "reviewId" value
 * @method PerformanceReviewReviewer setReviewerId()        Sets the current record's "reviewerId" value
 * @method PerformanceReviewReviewer setKpis()              Sets the current record's "kpis" value
 * @method PerformanceReview   		 setRatings()           Sets the current record's "ratings" value
 * @method PerformanceReviewReviewer setPerformanceReview() Sets the current record's "PerformanceReview" collection
 * @method PerformanceReviewReviewer setReviewer()          Sets the current record's "Reviewer" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Sunil Enadle
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerformanceReviewReviewer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_performance_review_reviewer');
        $this->hasColumn('id as id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 13,
             ));
        $this->hasColumn('review_id as reviewId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('reviewer_id as reviewerId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('kpis as kpis', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ratings as ratings', 'string', null, array(
        		'type' => 'string',
        ));
       $this->hasColumn('is_primary as isPrimary', 'integer', 1, array(
       		  'type' => 'integer',
        	  'length' => 1,
        	 ));
       $this->hasColumn('is_deleted as isDeleted', 'integer', 1, array(
       		  'type' => 'integer',
        	  'length' => 1,
        	 ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PerformanceReview', array(
             'local' => 'reviewId',
             'foreign' => 'id'));

        $this->hasOne('Employee as Reviewer', array(
             'local' => 'reviewerId',
             'foreign' => 'emp_number'));
    }
   
}