<?php

/**
 * BaseEmployeeMultiSourceFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empNumber
 * @property integer $reviewersNumber
 * @property text $positiveFeedback
 * @property text $negativeFeedback
 * @property text $impSuggestion
 * @property date $fromDate
 * @property date $toDate
 * @property date $updatedDate
 * @property date $createdDate
 * @property integer $updatedBy
 * @property integer $createdBy
 * @property integer $isSubmitted
 * @property integer $isDeleted
 * @property integer $isAnonymous
 * @property Employee $Employee
 * @property Employee $Reviewer
 * 
 * @method integer                     getId()               Returns the current record's "id" value
 * @method integer                     getEmpNumber()        Returns the current record's "empNumber" value
 * @method integer                     getReviewersNumber()  Returns the current record's "reviewersNumber" value
 * @method text                        getPositiveFeedback() Returns the current record's "positiveFeedback" value
 * @method text                        getNegativeFeedback() Returns the current record's "negativeFeedback" value
 * @method text                        getImpSuggestion()    Returns the current record's "impSuggestion" value
 * @method date                        getFromDate()         Returns the current record's "fromDate" value
 * @method date                        getToDate()           Returns the current record's "toDate" value
 * @method date                        getUpdatedDate()      Returns the current record's "updatedDate" value
 * @method date                        getCreatedDate()      Returns the current record's "createdDate" value
 * @method integer                     getUpdatedBy()        Returns the current record's "updatedBy" value
 * @method integer                     getCreatedBy()        Returns the current record's "createdBy" value
 * @method integer                     getIsSubmitted()      Returns the current record's "isSubmitted" value
 * @method integer                     getIsDeleted()        Returns the current record's "isDeleted" value
 * @method integer                     getIsAnonymous()      Returns the current record's "isAnonymous" value
 * @method Employee                    getEmployee()         Returns the current record's "Employee" value
 * @method Employee                    getReviewer()         Returns the current record's "Reviewer" value
 * @method EmployeeMultiSourceFeedback setId()               Sets the current record's "id" value
 * @method EmployeeMultiSourceFeedback setEmpNumber()        Sets the current record's "empNumber" value
 * @method EmployeeMultiSourceFeedback setReviewersNumber()  Sets the current record's "reviewersNumber" value
 * @method EmployeeMultiSourceFeedback setPositiveFeedback() Sets the current record's "positiveFeedback" value
 * @method EmployeeMultiSourceFeedback setNegativeFeedback() Sets the current record's "negativeFeedback" value
 * @method EmployeeMultiSourceFeedback setImpSuggestion()    Sets the current record's "impSuggestion" value
 * @method EmployeeMultiSourceFeedback setFromDate()         Sets the current record's "fromDate" value
 * @method EmployeeMultiSourceFeedback setToDate()           Sets the current record's "toDate" value
 * @method EmployeeMultiSourceFeedback setUpdatedDate()      Sets the current record's "updatedDate" value
 * @method EmployeeMultiSourceFeedback setCreatedDate()      Sets the current record's "createdDate" value
 * @method EmployeeMultiSourceFeedback setUpdatedBy()        Sets the current record's "updatedBy" value
 * @method EmployeeMultiSourceFeedback setCreatedBy()        Sets the current record's "createdBy" value
 * @method EmployeeMultiSourceFeedback setIsSubmitted()      Sets the current record's "isSubmitted" value
 * @method EmployeeMultiSourceFeedback setIsDeleted()        Sets the current record's "isDeleted" value
 * @method EmployeeMultiSourceFeedback setIsAnonymous()      Sets the current record's "isAnonymous" value
 * @method EmployeeMultiSourceFeedback setEmployee()         Sets the current record's "Employee" value
 * @method EmployeeMultiSourceFeedback setReviewer()         Sets the current record's "Reviewer" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployeeMultiSourceFeedback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_360_feedback');
        $this->hasColumn('id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 13,
             ));
        $this->hasColumn('emp_number as empNumber', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('reviewers_number as reviewersNumber', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('positive_feedback as positiveFeedback', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('negetive_feedback as negativeFeedback', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('improvement_suggestion as impSuggestion', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('from_date as fromDate', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('to_date as toDate', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('updated_date as updatedDate', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('created_date as createdDate', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('updated_by as updatedBy', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('created_by as createdBy', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('is_submitted as isSubmitted', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('is_deleted as isDeleted', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('is_anonymous as isAnonymous', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'empNumber',
             'foreign' => 'emp_number'));

        $this->hasOne('Employee as Reviewer', array(
             'local' => 'reviewersNumber',
             'foreign' => 'emp_number'));
    }
}