<?php

/**
 * BasePerformanceAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reviewId
 * @property string $fileName
 * @property string $fileType
 * @property integer $fileSize
 * @property blob $fileContent
 * @property integer $attachmentType
 * @property string $comment
 * @property integer $attachedBy
 * @property timestamp $attached_time
 * @property PerformanceReview $PerformanceReview
 * @property Employee $Employee
 * 
 * @method integer               getId()                Returns the current record's "id" value
 * @method integer               getReviewId()          Returns the current record's "reviewId" value
 * @method string                getFileName()          Returns the current record's "fileName" value
 * @method string                getFileType()          Returns the current record's "fileType" value
 * @method integer               getFileSize()          Returns the current record's "fileSize" value
 * @method blob                  getFileContent()       Returns the current record's "fileContent" value
 * @method integer               getAttachmentType()    Returns the current record's "attachmentType" value
 * @method string                getComment()           Returns the current record's "comment" value
 * @method integer               getAttachedBy()        Returns the current record's "attachedBy" value
 * @method timestamp             getAttachedDate()      Returns the current record's "attached_date" value
 * @method PerformanceReview     getPerformanceReview() Returns the current record's "PerformanceReview" value
 * @method Employee              getEmployee()          Returns the current record's "Employee" value
 * @method PerformanceAttachment setId()                Sets the current record's "id" value
 * @method PerformanceAttachment setReviewId()          Sets the current record's "reviewId" value
 * @method PerformanceAttachment setFileName()          Sets the current record's "fileName" value
 * @method PerformanceAttachment setFileType()          Sets the current record's "fileType" value
 * @method PerformanceAttachment setFileSize()          Sets the current record's "fileSize" value
 * @method PerformanceAttachment setFileContent()       Sets the current record's "fileContent" value
 * @method PerformanceAttachment setAttachmentType()    Sets the current record's "attachmentType" value
 * @method PerformanceAttachment setComment()           Sets the current record's "comment" value
 * @method PerformanceAttachment setAttachedBy()        Sets the current record's "attachedBy" value
 * @method PerformanceAttachment setAttachedDate()      Sets the current record's "attached_date" value
 * @method PerformanceAttachment setPerformanceReview() Sets the current record's "PerformanceReview" value
 * @method PerformanceAttachment setEmployee()          Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerformanceAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_performance_attachment');
        $this->hasColumn('id as id', 'integer', 13, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 13,
             ));
        $this->hasColumn('review_id as reviewId', 'integer', 13, array(
             'type' => 'integer',
             'length' => 13,
             ));
        $this->hasColumn('file_name as fileName', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_type as fileType', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_size as fileSize', 'integer', 30, array(
             'type' => 'integer',
             'length' => 30,
             ));
        $this->hasColumn('file_content as fileContent', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => 2147483647,
             ));
        $this->hasColumn('attachment_type as attachmentType', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('comment as comment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('attached_by as attachedBy', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('attached_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PerformanceReview', array(
             'local' => 'reviewId',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'attachedBy',
             'foreign' => 'emp_number'));
    }
}