<?php

/**
 * EmployeeProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmployeeProjectTable extends PluginEmployeeProjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmployeeProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmployeeProject');
    }
}