<?php

/**
 * EmployeeProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmployeeProjectHistoryTable extends PluginEmployeeProjectHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmployeeProjectHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmployeeProjectHistory');
    }
}