<?php

/**
 * PluginEmployeeProjectHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmployeeProjectHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmployeeProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmployeeProjectHistory');
    }
}