<?php

/**
 * PluginResetPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginResetPasswordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginResetPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginResetPassword');
    }
}