<?php

/**
 * PluginLeaveType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginLeaveType extends BaseLeaveType {
	
	const LEAVE_TYPE_PAID_LEAVE = 'Paid Leave';
    const LEAVE_TYPE_WFH = 'Work From Home';
    const LEAVE_TYPE_COFF = 'Comp off';
    const LEAVE_TYPE_MARRIAGE = 'Marriage Leave';
    const LEAVE_TYPE_PATERNITY = 'Paternity Leave';
    const LEAVE_TYPE_MATERNITY = 'Maternity Leave';
    const LEAVE_TYPE_UNPAID_LEAVE = 'Unpaid Leave';
    const LEAVE_TYPE_PAID_LEAVE_ID = 1;
    const LEAVE_TYPE_WFH_ID = 2;
    const LEAVE_TYPE_MARRIAGE_ID = 4;
    const LEAVE_TYPE_PATERNITY_ID = 5;
    const LEAVE_TYPE_MATERNITY_ID = 6;
    const LEAVE_TYPE_UNPAID_ID = 7;
    
    //Default values used when limit is not set in DB 
    const WFH_LIMIT_PER_MONTH = 3;
    const PAID_LEAVE_LIMIT = 21;
    const MARRIAGE_LEAVE_LIMIT = 1;
    const PATERNITY_LEAVE_LIMIT = 3;
    const MATERNITY_LEAVE_LIMIT = 90;
    const UNPAID_LEAVE_LIMIT = 30;
    
	public static $leaveTypeShort = array(
		self::LEAVE_TYPE_PAID_LEAVE    => 'PL',
		self::LEAVE_TYPE_WFH           => 'WFH',
		self::LEAVE_TYPE_COFF          => 'CO',
		self::LEAVE_TYPE_MARRIAGE      => 'ML',
		self::LEAVE_TYPE_MATERNITY     => 'MTL',
		self::LEAVE_TYPE_PATERNITY     => 'PTL',
		self::LEAVE_TYPE_UNPAID_LEAVE  => 'UL',
    );
    public function getDescriptiveLeaveTypeName() {
        return $this->getName() . (($this->getDeleted()) ? ' ('.__('Deleted').')' : '');
    }
}