<?php

/**
 * PluginLeaveCompOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveCompOffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveCompOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveCompOff');
    }
}