<?php

/**
 * PluginLeaveCompOff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginLeaveCompOff extends BaseLeaveCompOff
{
	
	/**
	 * @ignore
	 * @return type 
	 */
	public function getStatusText() {
		$statusId = $this->getStatus();
		return __(ucwords(strtolower(Leave::getTextForLeaveStatus($statusId))));
	}
}