<?php

/**
 * InterviewFeedbackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InterviewFeedbackTable extends PluginInterviewFeedbackTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object InterviewFeedbackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InterviewFeedback');
    }
}