<?php

/**
 * JobCandidateRequests
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Sunil Enadle
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobCandidateRequests extends PluginJobCandidateRequests
{
	const REQUEST_STATUS_PENDING = 1;
	const REQUEST_STATUS_DONE = 2;
	const REQUEST_STATUS_REJECT = 3;
	
	const REQUEST_TYPE_CHANGE_VACANCY = 1;
	
	public static $requestStatus = array(
		self::REQUEST_STATUS_PENDING => 'Pending',
		self::REQUEST_STATUS_DONE => 'Approved',
		self::REQUEST_STATUS_REJECT => 'Reject'       
	);
	
	/**
	 * Returns the name of candidate, (first middle last)
	 *
	 * @return String Full Name
	 */
	public function getCandidateName() {
		$candidateName = trim(trim($this->getJobCandidate()->getFirstName()) . " " . trim($this->getJobCandidate()->getLastName()));
		return $candidateName;
	}
	
	public function getOldVacancyName(){
		return $this->getOldJobVacancy()->getName();
	}
	
	public function getNewVacancyName(){
		return $this->getNewJobVacancy()->getName();
	}
	
	public function getRequesterName(){
		$empName = trim(trim($this->getEmployee()->getFirstName()) . " " . trim($this->getEmployee()->getLastName()));
		return $empName;
	}
	
	public function getStatusName(){
		if($this->request_status == 3){
			return 'Rejected';
		}else if($this->request_status == 2){
			return 'Approved';
		}else{
			return 'Pending';
		}
	}
	
	public function getDisplayCreatedDate(){
        return set_datepicker_date_format($this->createdDate);
    }
	
	
}