<?php

/**
 * JobCandidate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobCandidate extends PluginJobCandidate {
    const ACTIVE = 1;
    const ARCHIVED = 2;
    const TYPE = "CANDIDATE";
    const IS_DELETED = 1;
    const IS_NOT_DELETED = 0;

    const MODE_OF_APPLICATION_MANUAL = 1;
    const MODE_OF_APPLICATION_ONLINE = 2;
    public $candidateService;

    public function getFullName() {
        $middleName = trim($this->getMiddleName());
        return $this->getFirstName() . ' ' . (empty($middleName) ? '' : $middleName . ' ') . $this->getLastName();
    }
    
    
    public function getVacancyId() {
    	$candidateVacancy = $this->getJobCandidateVacancy();
    	return $candidateVacancy->getVacancyId();
    }
}
