<?php

/**
 * JobCandidateRequestsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobCandidateRequestsTable extends PluginJobCandidateRequestsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobCandidateRequestsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobCandidateRequests');
    }
}