<?php

/**
 * JobVacancyHiringManagerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobVacancyHiringManagerTable extends PluginJobVacancyHiringManagerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobVacancyHiringManagerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobVacancyHiringManager');
    }
}