<?php

/**
 * LeaveCompOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveCompOffTable extends PluginLeaveCompOffTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveCompOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveCompOff');
    }
}