<?php

/**
 * BaseEmployeeCertification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $certificationId
 * @property integer $emp_number
 * @property string $name
 * @property string $institute
 * @property date $date
 * @property string $grade
 * @property Employee $Employee
 * 
 * @method integer               getCertificationId() Returns the current record's "certificationId" value
 * @method integer               getEmpNumber()       Returns the current record's "emp_number" value
 * @method string                getName()            Returns the current record's "name" value
 * @method string                getInstitute()       Returns the current record's "institute" value
 * @method date                  getDate()            Returns the current record's "date" value
 * @method string                getGrade()           Returns the current record's "grade" value
 * @method Employee              getEmployee()        Returns the current record's "Employee" value
 * @method EmployeeCertification setCertificationId() Sets the current record's "certificationId" value
 * @method EmployeeCertification setEmpNumber()       Sets the current record's "emp_number" value
 * @method EmployeeCertification setName()            Sets the current record's "name" value
 * @method EmployeeCertification setInstitute()       Sets the current record's "institute" value
 * @method EmployeeCertification setDate()            Sets the current record's "date" value
 * @method EmployeeCertification setGrade()           Sets the current record's "grade" value
 * @method EmployeeCertification setEmployee()        Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployeeCertification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_certification');
        $this->hasColumn('certification_id as certificationId', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('institute', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('grade', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
		$this->hasColumn('approve', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
		$this->hasColumn('cattach_name', 'string', 100, array(
			 'type' => 'string',		 
			 'length' => 100,
		 ));
		 $this->hasColumn('cattach_type', 'string', 100, array(
			 'type' => 'string',		 
			 'length' => 100,
		 ));
		 $this->hasColumn('cattach_length', 'integer', 100, array(
			 'type' => 'integer',		 
			 'length' => 100,
		 ));
		$this->hasColumn('cattach', 'blob', array(
             'type' => 'blob',
         ));
		$this->hasColumn('certification_link as certificationLink', 'string', 100, array(
			 'type' => 'string',		 
			 'length' => 100,
		 ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}